// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stringdb.proto

#ifndef PROTOBUF_stringdb_2eproto__INCLUDED
#define PROTOBUF_stringdb_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace stringdb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_stringdb_2eproto();
void protobuf_AssignDesc_stringdb_2eproto();
void protobuf_ShutdownFile_stringdb_2eproto();

class Request;
class Request_RequestRead;
class Request_RequestRead_RequestReadData;
class Request_RequestWrite;
class Request_RequestWrite_RequestWriteData;
class Request_RequestWrite_RequestWriteData_AttributeData;
class Response;
class Response_ResponseRead;
class Response_ResponseRead_ResponseReadData;
class Response_ResponseRead_ResponseReadData_AttributeData;
class Response_ResponseWrite;
class Response_ResponseWrite_ResponseWriteData;
class Response_ResponseWrite_ResponseWriteData_WriteData;

enum RequestAndResponseType {
  READ = 1,
  WRITE = 2
};
bool RequestAndResponseType_IsValid(int value);
const RequestAndResponseType RequestAndResponseType_MIN = READ;
const RequestAndResponseType RequestAndResponseType_MAX = WRITE;
const int RequestAndResponseType_ARRAYSIZE = RequestAndResponseType_MAX + 1;

const ::google::protobuf::EnumDescriptor* RequestAndResponseType_descriptor();
inline const ::std::string& RequestAndResponseType_Name(RequestAndResponseType value) {
  return ::google::protobuf::internal::NameOfEnum(
    RequestAndResponseType_descriptor(), value);
}
inline bool RequestAndResponseType_Parse(
    const ::std::string& name, RequestAndResponseType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RequestAndResponseType>(
    RequestAndResponseType_descriptor(), name, value);
}
// ===================================================================

class Request_RequestRead_RequestReadData : public ::google::protobuf::Message {
 public:
  Request_RequestRead_RequestReadData();
  virtual ~Request_RequestRead_RequestReadData();

  Request_RequestRead_RequestReadData(const Request_RequestRead_RequestReadData& from);

  inline Request_RequestRead_RequestReadData& operator=(const Request_RequestRead_RequestReadData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request_RequestRead_RequestReadData& default_instance();

  void Swap(Request_RequestRead_RequestReadData* other);

  // implements Message ----------------------------------------------

  Request_RequestRead_RequestReadData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request_RequestRead_RequestReadData& from);
  void MergeFrom(const Request_RequestRead_RequestReadData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 application_id = 1;
  inline bool has_application_id() const;
  inline void clear_application_id();
  static const int kApplicationIdFieldNumber = 1;
  inline ::google::protobuf::int32 application_id() const;
  inline void set_application_id(::google::protobuf::int32 value);

  // repeated int32 attribute_id = 3;
  inline int attribute_id_size() const;
  inline void clear_attribute_id();
  static const int kAttributeIdFieldNumber = 3;
  inline ::google::protobuf::int32 attribute_id(int index) const;
  inline void set_attribute_id(int index, ::google::protobuf::int32 value);
  inline void add_attribute_id(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      attribute_id() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_attribute_id();

  // @@protoc_insertion_point(class_scope:stringdb.Request.RequestRead.RequestReadData)
 private:
  inline void set_has_application_id();
  inline void clear_has_application_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > attribute_id_;
  ::google::protobuf::int32 application_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_stringdb_2eproto();
  friend void protobuf_AssignDesc_stringdb_2eproto();
  friend void protobuf_ShutdownFile_stringdb_2eproto();

  void InitAsDefaultInstance();
  static Request_RequestRead_RequestReadData* default_instance_;
};
// -------------------------------------------------------------------

class Request_RequestRead : public ::google::protobuf::Message {
 public:
  Request_RequestRead();
  virtual ~Request_RequestRead();

  Request_RequestRead(const Request_RequestRead& from);

  inline Request_RequestRead& operator=(const Request_RequestRead& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request_RequestRead& default_instance();

  void Swap(Request_RequestRead* other);

  // implements Message ----------------------------------------------

  Request_RequestRead* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request_RequestRead& from);
  void MergeFrom(const Request_RequestRead& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Request_RequestRead_RequestReadData RequestReadData;

  // accessors -------------------------------------------------------

  // optional .stringdb.Request.RequestRead.RequestReadData request_read_data = 21;
  inline bool has_request_read_data() const;
  inline void clear_request_read_data();
  static const int kRequestReadDataFieldNumber = 21;
  inline const ::stringdb::Request_RequestRead_RequestReadData& request_read_data() const;
  inline ::stringdb::Request_RequestRead_RequestReadData* mutable_request_read_data();
  inline ::stringdb::Request_RequestRead_RequestReadData* release_request_read_data();
  inline void set_allocated_request_read_data(::stringdb::Request_RequestRead_RequestReadData* request_read_data);

  // @@protoc_insertion_point(class_scope:stringdb.Request.RequestRead)
 private:
  inline void set_has_request_read_data();
  inline void clear_has_request_read_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::stringdb::Request_RequestRead_RequestReadData* request_read_data_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_stringdb_2eproto();
  friend void protobuf_AssignDesc_stringdb_2eproto();
  friend void protobuf_ShutdownFile_stringdb_2eproto();

  void InitAsDefaultInstance();
  static Request_RequestRead* default_instance_;
};
// -------------------------------------------------------------------

class Request_RequestWrite_RequestWriteData_AttributeData : public ::google::protobuf::Message {
 public:
  Request_RequestWrite_RequestWriteData_AttributeData();
  virtual ~Request_RequestWrite_RequestWriteData_AttributeData();

  Request_RequestWrite_RequestWriteData_AttributeData(const Request_RequestWrite_RequestWriteData_AttributeData& from);

  inline Request_RequestWrite_RequestWriteData_AttributeData& operator=(const Request_RequestWrite_RequestWriteData_AttributeData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request_RequestWrite_RequestWriteData_AttributeData& default_instance();

  void Swap(Request_RequestWrite_RequestWriteData_AttributeData* other);

  // implements Message ----------------------------------------------

  Request_RequestWrite_RequestWriteData_AttributeData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request_RequestWrite_RequestWriteData_AttributeData& from);
  void MergeFrom(const Request_RequestWrite_RequestWriteData_AttributeData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 attribute_id = 1;
  inline bool has_attribute_id() const;
  inline void clear_attribute_id();
  static const int kAttributeIdFieldNumber = 1;
  inline ::google::protobuf::int32 attribute_id() const;
  inline void set_attribute_id(::google::protobuf::int32 value);

  // required string attribute_value = 2;
  inline bool has_attribute_value() const;
  inline void clear_attribute_value();
  static const int kAttributeValueFieldNumber = 2;
  inline const ::std::string& attribute_value() const;
  inline void set_attribute_value(const ::std::string& value);
  inline void set_attribute_value(const char* value);
  inline void set_attribute_value(const char* value, size_t size);
  inline ::std::string* mutable_attribute_value();
  inline ::std::string* release_attribute_value();
  inline void set_allocated_attribute_value(::std::string* attribute_value);

  // @@protoc_insertion_point(class_scope:stringdb.Request.RequestWrite.RequestWriteData.AttributeData)
 private:
  inline void set_has_attribute_id();
  inline void clear_has_attribute_id();
  inline void set_has_attribute_value();
  inline void clear_has_attribute_value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* attribute_value_;
  ::google::protobuf::int32 attribute_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_stringdb_2eproto();
  friend void protobuf_AssignDesc_stringdb_2eproto();
  friend void protobuf_ShutdownFile_stringdb_2eproto();

  void InitAsDefaultInstance();
  static Request_RequestWrite_RequestWriteData_AttributeData* default_instance_;
};
// -------------------------------------------------------------------

class Request_RequestWrite_RequestWriteData : public ::google::protobuf::Message {
 public:
  Request_RequestWrite_RequestWriteData();
  virtual ~Request_RequestWrite_RequestWriteData();

  Request_RequestWrite_RequestWriteData(const Request_RequestWrite_RequestWriteData& from);

  inline Request_RequestWrite_RequestWriteData& operator=(const Request_RequestWrite_RequestWriteData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request_RequestWrite_RequestWriteData& default_instance();

  void Swap(Request_RequestWrite_RequestWriteData* other);

  // implements Message ----------------------------------------------

  Request_RequestWrite_RequestWriteData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request_RequestWrite_RequestWriteData& from);
  void MergeFrom(const Request_RequestWrite_RequestWriteData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Request_RequestWrite_RequestWriteData_AttributeData AttributeData;

  // accessors -------------------------------------------------------

  // required int32 application_id = 1;
  inline bool has_application_id() const;
  inline void clear_application_id();
  static const int kApplicationIdFieldNumber = 1;
  inline ::google::protobuf::int32 application_id() const;
  inline void set_application_id(::google::protobuf::int32 value);

  // repeated .stringdb.Request.RequestWrite.RequestWriteData.AttributeData attribute_data = 21;
  inline int attribute_data_size() const;
  inline void clear_attribute_data();
  static const int kAttributeDataFieldNumber = 21;
  inline const ::stringdb::Request_RequestWrite_RequestWriteData_AttributeData& attribute_data(int index) const;
  inline ::stringdb::Request_RequestWrite_RequestWriteData_AttributeData* mutable_attribute_data(int index);
  inline ::stringdb::Request_RequestWrite_RequestWriteData_AttributeData* add_attribute_data();
  inline const ::google::protobuf::RepeatedPtrField< ::stringdb::Request_RequestWrite_RequestWriteData_AttributeData >&
      attribute_data() const;
  inline ::google::protobuf::RepeatedPtrField< ::stringdb::Request_RequestWrite_RequestWriteData_AttributeData >*
      mutable_attribute_data();

  // @@protoc_insertion_point(class_scope:stringdb.Request.RequestWrite.RequestWriteData)
 private:
  inline void set_has_application_id();
  inline void clear_has_application_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::stringdb::Request_RequestWrite_RequestWriteData_AttributeData > attribute_data_;
  ::google::protobuf::int32 application_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_stringdb_2eproto();
  friend void protobuf_AssignDesc_stringdb_2eproto();
  friend void protobuf_ShutdownFile_stringdb_2eproto();

  void InitAsDefaultInstance();
  static Request_RequestWrite_RequestWriteData* default_instance_;
};
// -------------------------------------------------------------------

class Request_RequestWrite : public ::google::protobuf::Message {
 public:
  Request_RequestWrite();
  virtual ~Request_RequestWrite();

  Request_RequestWrite(const Request_RequestWrite& from);

  inline Request_RequestWrite& operator=(const Request_RequestWrite& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request_RequestWrite& default_instance();

  void Swap(Request_RequestWrite* other);

  // implements Message ----------------------------------------------

  Request_RequestWrite* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request_RequestWrite& from);
  void MergeFrom(const Request_RequestWrite& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Request_RequestWrite_RequestWriteData RequestWriteData;

  // accessors -------------------------------------------------------

  // optional .stringdb.Request.RequestWrite.RequestWriteData request_write_data = 21;
  inline bool has_request_write_data() const;
  inline void clear_request_write_data();
  static const int kRequestWriteDataFieldNumber = 21;
  inline const ::stringdb::Request_RequestWrite_RequestWriteData& request_write_data() const;
  inline ::stringdb::Request_RequestWrite_RequestWriteData* mutable_request_write_data();
  inline ::stringdb::Request_RequestWrite_RequestWriteData* release_request_write_data();
  inline void set_allocated_request_write_data(::stringdb::Request_RequestWrite_RequestWriteData* request_write_data);

  // @@protoc_insertion_point(class_scope:stringdb.Request.RequestWrite)
 private:
  inline void set_has_request_write_data();
  inline void clear_has_request_write_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::stringdb::Request_RequestWrite_RequestWriteData* request_write_data_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_stringdb_2eproto();
  friend void protobuf_AssignDesc_stringdb_2eproto();
  friend void protobuf_ShutdownFile_stringdb_2eproto();

  void InitAsDefaultInstance();
  static Request_RequestWrite* default_instance_;
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  void Swap(Request* other);

  // implements Message ----------------------------------------------

  Request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Request_RequestRead RequestRead;
  typedef Request_RequestWrite RequestWrite;

  // accessors -------------------------------------------------------

  // required .stringdb.RequestAndResponseType type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::stringdb::RequestAndResponseType type() const;
  inline void set_type(::stringdb::RequestAndResponseType value);

  // optional .stringdb.Request.RequestRead request_read = 21;
  inline bool has_request_read() const;
  inline void clear_request_read();
  static const int kRequestReadFieldNumber = 21;
  inline const ::stringdb::Request_RequestRead& request_read() const;
  inline ::stringdb::Request_RequestRead* mutable_request_read();
  inline ::stringdb::Request_RequestRead* release_request_read();
  inline void set_allocated_request_read(::stringdb::Request_RequestRead* request_read);

  // optional .stringdb.Request.RequestWrite request_write = 22;
  inline bool has_request_write() const;
  inline void clear_request_write();
  static const int kRequestWriteFieldNumber = 22;
  inline const ::stringdb::Request_RequestWrite& request_write() const;
  inline ::stringdb::Request_RequestWrite* mutable_request_write();
  inline ::stringdb::Request_RequestWrite* release_request_write();
  inline void set_allocated_request_write(::stringdb::Request_RequestWrite* request_write);

  // @@protoc_insertion_point(class_scope:stringdb.Request)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_request_read();
  inline void clear_has_request_read();
  inline void set_has_request_write();
  inline void clear_has_request_write();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::stringdb::Request_RequestRead* request_read_;
  ::stringdb::Request_RequestWrite* request_write_;
  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_stringdb_2eproto();
  friend void protobuf_AssignDesc_stringdb_2eproto();
  friend void protobuf_ShutdownFile_stringdb_2eproto();

  void InitAsDefaultInstance();
  static Request* default_instance_;
};
// -------------------------------------------------------------------

class Response_ResponseRead_ResponseReadData_AttributeData : public ::google::protobuf::Message {
 public:
  Response_ResponseRead_ResponseReadData_AttributeData();
  virtual ~Response_ResponseRead_ResponseReadData_AttributeData();

  Response_ResponseRead_ResponseReadData_AttributeData(const Response_ResponseRead_ResponseReadData_AttributeData& from);

  inline Response_ResponseRead_ResponseReadData_AttributeData& operator=(const Response_ResponseRead_ResponseReadData_AttributeData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response_ResponseRead_ResponseReadData_AttributeData& default_instance();

  void Swap(Response_ResponseRead_ResponseReadData_AttributeData* other);

  // implements Message ----------------------------------------------

  Response_ResponseRead_ResponseReadData_AttributeData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response_ResponseRead_ResponseReadData_AttributeData& from);
  void MergeFrom(const Response_ResponseRead_ResponseReadData_AttributeData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 attribute_id = 1;
  inline bool has_attribute_id() const;
  inline void clear_attribute_id();
  static const int kAttributeIdFieldNumber = 1;
  inline ::google::protobuf::int32 attribute_id() const;
  inline void set_attribute_id(::google::protobuf::int32 value);

  // required string attribute_value = 2;
  inline bool has_attribute_value() const;
  inline void clear_attribute_value();
  static const int kAttributeValueFieldNumber = 2;
  inline const ::std::string& attribute_value() const;
  inline void set_attribute_value(const ::std::string& value);
  inline void set_attribute_value(const char* value);
  inline void set_attribute_value(const char* value, size_t size);
  inline ::std::string* mutable_attribute_value();
  inline ::std::string* release_attribute_value();
  inline void set_allocated_attribute_value(::std::string* attribute_value);

  // @@protoc_insertion_point(class_scope:stringdb.Response.ResponseRead.ResponseReadData.AttributeData)
 private:
  inline void set_has_attribute_id();
  inline void clear_has_attribute_id();
  inline void set_has_attribute_value();
  inline void clear_has_attribute_value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* attribute_value_;
  ::google::protobuf::int32 attribute_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_stringdb_2eproto();
  friend void protobuf_AssignDesc_stringdb_2eproto();
  friend void protobuf_ShutdownFile_stringdb_2eproto();

  void InitAsDefaultInstance();
  static Response_ResponseRead_ResponseReadData_AttributeData* default_instance_;
};
// -------------------------------------------------------------------

class Response_ResponseRead_ResponseReadData : public ::google::protobuf::Message {
 public:
  Response_ResponseRead_ResponseReadData();
  virtual ~Response_ResponseRead_ResponseReadData();

  Response_ResponseRead_ResponseReadData(const Response_ResponseRead_ResponseReadData& from);

  inline Response_ResponseRead_ResponseReadData& operator=(const Response_ResponseRead_ResponseReadData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response_ResponseRead_ResponseReadData& default_instance();

  void Swap(Response_ResponseRead_ResponseReadData* other);

  // implements Message ----------------------------------------------

  Response_ResponseRead_ResponseReadData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response_ResponseRead_ResponseReadData& from);
  void MergeFrom(const Response_ResponseRead_ResponseReadData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Response_ResponseRead_ResponseReadData_AttributeData AttributeData;

  // accessors -------------------------------------------------------

  // required int32 application_id = 1;
  inline bool has_application_id() const;
  inline void clear_application_id();
  static const int kApplicationIdFieldNumber = 1;
  inline ::google::protobuf::int32 application_id() const;
  inline void set_application_id(::google::protobuf::int32 value);

  // repeated .stringdb.Response.ResponseRead.ResponseReadData.AttributeData attribute_data = 21;
  inline int attribute_data_size() const;
  inline void clear_attribute_data();
  static const int kAttributeDataFieldNumber = 21;
  inline const ::stringdb::Response_ResponseRead_ResponseReadData_AttributeData& attribute_data(int index) const;
  inline ::stringdb::Response_ResponseRead_ResponseReadData_AttributeData* mutable_attribute_data(int index);
  inline ::stringdb::Response_ResponseRead_ResponseReadData_AttributeData* add_attribute_data();
  inline const ::google::protobuf::RepeatedPtrField< ::stringdb::Response_ResponseRead_ResponseReadData_AttributeData >&
      attribute_data() const;
  inline ::google::protobuf::RepeatedPtrField< ::stringdb::Response_ResponseRead_ResponseReadData_AttributeData >*
      mutable_attribute_data();

  // @@protoc_insertion_point(class_scope:stringdb.Response.ResponseRead.ResponseReadData)
 private:
  inline void set_has_application_id();
  inline void clear_has_application_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::stringdb::Response_ResponseRead_ResponseReadData_AttributeData > attribute_data_;
  ::google::protobuf::int32 application_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_stringdb_2eproto();
  friend void protobuf_AssignDesc_stringdb_2eproto();
  friend void protobuf_ShutdownFile_stringdb_2eproto();

  void InitAsDefaultInstance();
  static Response_ResponseRead_ResponseReadData* default_instance_;
};
// -------------------------------------------------------------------

class Response_ResponseRead : public ::google::protobuf::Message {
 public:
  Response_ResponseRead();
  virtual ~Response_ResponseRead();

  Response_ResponseRead(const Response_ResponseRead& from);

  inline Response_ResponseRead& operator=(const Response_ResponseRead& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response_ResponseRead& default_instance();

  void Swap(Response_ResponseRead* other);

  // implements Message ----------------------------------------------

  Response_ResponseRead* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response_ResponseRead& from);
  void MergeFrom(const Response_ResponseRead& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Response_ResponseRead_ResponseReadData ResponseReadData;

  // accessors -------------------------------------------------------

  // optional .stringdb.Response.ResponseRead.ResponseReadData response_read_data = 21;
  inline bool has_response_read_data() const;
  inline void clear_response_read_data();
  static const int kResponseReadDataFieldNumber = 21;
  inline const ::stringdb::Response_ResponseRead_ResponseReadData& response_read_data() const;
  inline ::stringdb::Response_ResponseRead_ResponseReadData* mutable_response_read_data();
  inline ::stringdb::Response_ResponseRead_ResponseReadData* release_response_read_data();
  inline void set_allocated_response_read_data(::stringdb::Response_ResponseRead_ResponseReadData* response_read_data);

  // @@protoc_insertion_point(class_scope:stringdb.Response.ResponseRead)
 private:
  inline void set_has_response_read_data();
  inline void clear_has_response_read_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::stringdb::Response_ResponseRead_ResponseReadData* response_read_data_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_stringdb_2eproto();
  friend void protobuf_AssignDesc_stringdb_2eproto();
  friend void protobuf_ShutdownFile_stringdb_2eproto();

  void InitAsDefaultInstance();
  static Response_ResponseRead* default_instance_;
};
// -------------------------------------------------------------------

class Response_ResponseWrite_ResponseWriteData_WriteData : public ::google::protobuf::Message {
 public:
  Response_ResponseWrite_ResponseWriteData_WriteData();
  virtual ~Response_ResponseWrite_ResponseWriteData_WriteData();

  Response_ResponseWrite_ResponseWriteData_WriteData(const Response_ResponseWrite_ResponseWriteData_WriteData& from);

  inline Response_ResponseWrite_ResponseWriteData_WriteData& operator=(const Response_ResponseWrite_ResponseWriteData_WriteData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response_ResponseWrite_ResponseWriteData_WriteData& default_instance();

  void Swap(Response_ResponseWrite_ResponseWriteData_WriteData* other);

  // implements Message ----------------------------------------------

  Response_ResponseWrite_ResponseWriteData_WriteData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response_ResponseWrite_ResponseWriteData_WriteData& from);
  void MergeFrom(const Response_ResponseWrite_ResponseWriteData_WriteData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 attribute_id = 1;
  inline bool has_attribute_id() const;
  inline void clear_attribute_id();
  static const int kAttributeIdFieldNumber = 1;
  inline ::google::protobuf::int32 attribute_id() const;
  inline void set_attribute_id(::google::protobuf::int32 value);

  // required int32 error_number = 2;
  inline bool has_error_number() const;
  inline void clear_error_number();
  static const int kErrorNumberFieldNumber = 2;
  inline ::google::protobuf::int32 error_number() const;
  inline void set_error_number(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:stringdb.Response.ResponseWrite.ResponseWriteData.WriteData)
 private:
  inline void set_has_attribute_id();
  inline void clear_has_attribute_id();
  inline void set_has_error_number();
  inline void clear_has_error_number();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 attribute_id_;
  ::google::protobuf::int32 error_number_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_stringdb_2eproto();
  friend void protobuf_AssignDesc_stringdb_2eproto();
  friend void protobuf_ShutdownFile_stringdb_2eproto();

  void InitAsDefaultInstance();
  static Response_ResponseWrite_ResponseWriteData_WriteData* default_instance_;
};
// -------------------------------------------------------------------

class Response_ResponseWrite_ResponseWriteData : public ::google::protobuf::Message {
 public:
  Response_ResponseWrite_ResponseWriteData();
  virtual ~Response_ResponseWrite_ResponseWriteData();

  Response_ResponseWrite_ResponseWriteData(const Response_ResponseWrite_ResponseWriteData& from);

  inline Response_ResponseWrite_ResponseWriteData& operator=(const Response_ResponseWrite_ResponseWriteData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response_ResponseWrite_ResponseWriteData& default_instance();

  void Swap(Response_ResponseWrite_ResponseWriteData* other);

  // implements Message ----------------------------------------------

  Response_ResponseWrite_ResponseWriteData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response_ResponseWrite_ResponseWriteData& from);
  void MergeFrom(const Response_ResponseWrite_ResponseWriteData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Response_ResponseWrite_ResponseWriteData_WriteData WriteData;

  // accessors -------------------------------------------------------

  // required int32 application_id = 1;
  inline bool has_application_id() const;
  inline void clear_application_id();
  static const int kApplicationIdFieldNumber = 1;
  inline ::google::protobuf::int32 application_id() const;
  inline void set_application_id(::google::protobuf::int32 value);

  // repeated .stringdb.Response.ResponseWrite.ResponseWriteData.WriteData write_data = 21;
  inline int write_data_size() const;
  inline void clear_write_data();
  static const int kWriteDataFieldNumber = 21;
  inline const ::stringdb::Response_ResponseWrite_ResponseWriteData_WriteData& write_data(int index) const;
  inline ::stringdb::Response_ResponseWrite_ResponseWriteData_WriteData* mutable_write_data(int index);
  inline ::stringdb::Response_ResponseWrite_ResponseWriteData_WriteData* add_write_data();
  inline const ::google::protobuf::RepeatedPtrField< ::stringdb::Response_ResponseWrite_ResponseWriteData_WriteData >&
      write_data() const;
  inline ::google::protobuf::RepeatedPtrField< ::stringdb::Response_ResponseWrite_ResponseWriteData_WriteData >*
      mutable_write_data();

  // @@protoc_insertion_point(class_scope:stringdb.Response.ResponseWrite.ResponseWriteData)
 private:
  inline void set_has_application_id();
  inline void clear_has_application_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::stringdb::Response_ResponseWrite_ResponseWriteData_WriteData > write_data_;
  ::google::protobuf::int32 application_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_stringdb_2eproto();
  friend void protobuf_AssignDesc_stringdb_2eproto();
  friend void protobuf_ShutdownFile_stringdb_2eproto();

  void InitAsDefaultInstance();
  static Response_ResponseWrite_ResponseWriteData* default_instance_;
};
// -------------------------------------------------------------------

class Response_ResponseWrite : public ::google::protobuf::Message {
 public:
  Response_ResponseWrite();
  virtual ~Response_ResponseWrite();

  Response_ResponseWrite(const Response_ResponseWrite& from);

  inline Response_ResponseWrite& operator=(const Response_ResponseWrite& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response_ResponseWrite& default_instance();

  void Swap(Response_ResponseWrite* other);

  // implements Message ----------------------------------------------

  Response_ResponseWrite* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response_ResponseWrite& from);
  void MergeFrom(const Response_ResponseWrite& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Response_ResponseWrite_ResponseWriteData ResponseWriteData;

  // accessors -------------------------------------------------------

  // optional .stringdb.Response.ResponseWrite.ResponseWriteData response_write_data = 21;
  inline bool has_response_write_data() const;
  inline void clear_response_write_data();
  static const int kResponseWriteDataFieldNumber = 21;
  inline const ::stringdb::Response_ResponseWrite_ResponseWriteData& response_write_data() const;
  inline ::stringdb::Response_ResponseWrite_ResponseWriteData* mutable_response_write_data();
  inline ::stringdb::Response_ResponseWrite_ResponseWriteData* release_response_write_data();
  inline void set_allocated_response_write_data(::stringdb::Response_ResponseWrite_ResponseWriteData* response_write_data);

  // @@protoc_insertion_point(class_scope:stringdb.Response.ResponseWrite)
 private:
  inline void set_has_response_write_data();
  inline void clear_has_response_write_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::stringdb::Response_ResponseWrite_ResponseWriteData* response_write_data_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_stringdb_2eproto();
  friend void protobuf_AssignDesc_stringdb_2eproto();
  friend void protobuf_ShutdownFile_stringdb_2eproto();

  void InitAsDefaultInstance();
  static Response_ResponseWrite* default_instance_;
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  void Swap(Response* other);

  // implements Message ----------------------------------------------

  Response* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Response_ResponseRead ResponseRead;
  typedef Response_ResponseWrite ResponseWrite;

  // accessors -------------------------------------------------------

  // required .stringdb.RequestAndResponseType type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::stringdb::RequestAndResponseType type() const;
  inline void set_type(::stringdb::RequestAndResponseType value);

  // optional .stringdb.Response.ResponseRead response_read = 21;
  inline bool has_response_read() const;
  inline void clear_response_read();
  static const int kResponseReadFieldNumber = 21;
  inline const ::stringdb::Response_ResponseRead& response_read() const;
  inline ::stringdb::Response_ResponseRead* mutable_response_read();
  inline ::stringdb::Response_ResponseRead* release_response_read();
  inline void set_allocated_response_read(::stringdb::Response_ResponseRead* response_read);

  // optional .stringdb.Response.ResponseWrite response_write = 22;
  inline bool has_response_write() const;
  inline void clear_response_write();
  static const int kResponseWriteFieldNumber = 22;
  inline const ::stringdb::Response_ResponseWrite& response_write() const;
  inline ::stringdb::Response_ResponseWrite* mutable_response_write();
  inline ::stringdb::Response_ResponseWrite* release_response_write();
  inline void set_allocated_response_write(::stringdb::Response_ResponseWrite* response_write);

  // @@protoc_insertion_point(class_scope:stringdb.Response)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_response_read();
  inline void clear_has_response_read();
  inline void set_has_response_write();
  inline void clear_has_response_write();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::stringdb::Response_ResponseRead* response_read_;
  ::stringdb::Response_ResponseWrite* response_write_;
  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_stringdb_2eproto();
  friend void protobuf_AssignDesc_stringdb_2eproto();
  friend void protobuf_ShutdownFile_stringdb_2eproto();

  void InitAsDefaultInstance();
  static Response* default_instance_;
};
// ===================================================================


// ===================================================================

// Request_RequestRead_RequestReadData

// required int32 application_id = 1;
inline bool Request_RequestRead_RequestReadData::has_application_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request_RequestRead_RequestReadData::set_has_application_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request_RequestRead_RequestReadData::clear_has_application_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request_RequestRead_RequestReadData::clear_application_id() {
  application_id_ = 0;
  clear_has_application_id();
}
inline ::google::protobuf::int32 Request_RequestRead_RequestReadData::application_id() const {
  return application_id_;
}
inline void Request_RequestRead_RequestReadData::set_application_id(::google::protobuf::int32 value) {
  set_has_application_id();
  application_id_ = value;
}

// repeated int32 attribute_id = 3;
inline int Request_RequestRead_RequestReadData::attribute_id_size() const {
  return attribute_id_.size();
}
inline void Request_RequestRead_RequestReadData::clear_attribute_id() {
  attribute_id_.Clear();
}
inline ::google::protobuf::int32 Request_RequestRead_RequestReadData::attribute_id(int index) const {
  return attribute_id_.Get(index);
}
inline void Request_RequestRead_RequestReadData::set_attribute_id(int index, ::google::protobuf::int32 value) {
  attribute_id_.Set(index, value);
}
inline void Request_RequestRead_RequestReadData::add_attribute_id(::google::protobuf::int32 value) {
  attribute_id_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Request_RequestRead_RequestReadData::attribute_id() const {
  return attribute_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Request_RequestRead_RequestReadData::mutable_attribute_id() {
  return &attribute_id_;
}

// -------------------------------------------------------------------

// Request_RequestRead

// optional .stringdb.Request.RequestRead.RequestReadData request_read_data = 21;
inline bool Request_RequestRead::has_request_read_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request_RequestRead::set_has_request_read_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request_RequestRead::clear_has_request_read_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request_RequestRead::clear_request_read_data() {
  if (request_read_data_ != NULL) request_read_data_->::stringdb::Request_RequestRead_RequestReadData::Clear();
  clear_has_request_read_data();
}
inline const ::stringdb::Request_RequestRead_RequestReadData& Request_RequestRead::request_read_data() const {
  return request_read_data_ != NULL ? *request_read_data_ : *default_instance_->request_read_data_;
}
inline ::stringdb::Request_RequestRead_RequestReadData* Request_RequestRead::mutable_request_read_data() {
  set_has_request_read_data();
  if (request_read_data_ == NULL) request_read_data_ = new ::stringdb::Request_RequestRead_RequestReadData;
  return request_read_data_;
}
inline ::stringdb::Request_RequestRead_RequestReadData* Request_RequestRead::release_request_read_data() {
  clear_has_request_read_data();
  ::stringdb::Request_RequestRead_RequestReadData* temp = request_read_data_;
  request_read_data_ = NULL;
  return temp;
}
inline void Request_RequestRead::set_allocated_request_read_data(::stringdb::Request_RequestRead_RequestReadData* request_read_data) {
  delete request_read_data_;
  request_read_data_ = request_read_data;
  if (request_read_data) {
    set_has_request_read_data();
  } else {
    clear_has_request_read_data();
  }
}

// -------------------------------------------------------------------

// Request_RequestWrite_RequestWriteData_AttributeData

// required int32 attribute_id = 1;
inline bool Request_RequestWrite_RequestWriteData_AttributeData::has_attribute_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request_RequestWrite_RequestWriteData_AttributeData::set_has_attribute_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request_RequestWrite_RequestWriteData_AttributeData::clear_has_attribute_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request_RequestWrite_RequestWriteData_AttributeData::clear_attribute_id() {
  attribute_id_ = 0;
  clear_has_attribute_id();
}
inline ::google::protobuf::int32 Request_RequestWrite_RequestWriteData_AttributeData::attribute_id() const {
  return attribute_id_;
}
inline void Request_RequestWrite_RequestWriteData_AttributeData::set_attribute_id(::google::protobuf::int32 value) {
  set_has_attribute_id();
  attribute_id_ = value;
}

// required string attribute_value = 2;
inline bool Request_RequestWrite_RequestWriteData_AttributeData::has_attribute_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Request_RequestWrite_RequestWriteData_AttributeData::set_has_attribute_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Request_RequestWrite_RequestWriteData_AttributeData::clear_has_attribute_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Request_RequestWrite_RequestWriteData_AttributeData::clear_attribute_value() {
  if (attribute_value_ != &::google::protobuf::internal::kEmptyString) {
    attribute_value_->clear();
  }
  clear_has_attribute_value();
}
inline const ::std::string& Request_RequestWrite_RequestWriteData_AttributeData::attribute_value() const {
  return *attribute_value_;
}
inline void Request_RequestWrite_RequestWriteData_AttributeData::set_attribute_value(const ::std::string& value) {
  set_has_attribute_value();
  if (attribute_value_ == &::google::protobuf::internal::kEmptyString) {
    attribute_value_ = new ::std::string;
  }
  attribute_value_->assign(value);
}
inline void Request_RequestWrite_RequestWriteData_AttributeData::set_attribute_value(const char* value) {
  set_has_attribute_value();
  if (attribute_value_ == &::google::protobuf::internal::kEmptyString) {
    attribute_value_ = new ::std::string;
  }
  attribute_value_->assign(value);
}
inline void Request_RequestWrite_RequestWriteData_AttributeData::set_attribute_value(const char* value, size_t size) {
  set_has_attribute_value();
  if (attribute_value_ == &::google::protobuf::internal::kEmptyString) {
    attribute_value_ = new ::std::string;
  }
  attribute_value_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Request_RequestWrite_RequestWriteData_AttributeData::mutable_attribute_value() {
  set_has_attribute_value();
  if (attribute_value_ == &::google::protobuf::internal::kEmptyString) {
    attribute_value_ = new ::std::string;
  }
  return attribute_value_;
}
inline ::std::string* Request_RequestWrite_RequestWriteData_AttributeData::release_attribute_value() {
  clear_has_attribute_value();
  if (attribute_value_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = attribute_value_;
    attribute_value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Request_RequestWrite_RequestWriteData_AttributeData::set_allocated_attribute_value(::std::string* attribute_value) {
  if (attribute_value_ != &::google::protobuf::internal::kEmptyString) {
    delete attribute_value_;
  }
  if (attribute_value) {
    set_has_attribute_value();
    attribute_value_ = attribute_value;
  } else {
    clear_has_attribute_value();
    attribute_value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// Request_RequestWrite_RequestWriteData

// required int32 application_id = 1;
inline bool Request_RequestWrite_RequestWriteData::has_application_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request_RequestWrite_RequestWriteData::set_has_application_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request_RequestWrite_RequestWriteData::clear_has_application_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request_RequestWrite_RequestWriteData::clear_application_id() {
  application_id_ = 0;
  clear_has_application_id();
}
inline ::google::protobuf::int32 Request_RequestWrite_RequestWriteData::application_id() const {
  return application_id_;
}
inline void Request_RequestWrite_RequestWriteData::set_application_id(::google::protobuf::int32 value) {
  set_has_application_id();
  application_id_ = value;
}

// repeated .stringdb.Request.RequestWrite.RequestWriteData.AttributeData attribute_data = 21;
inline int Request_RequestWrite_RequestWriteData::attribute_data_size() const {
  return attribute_data_.size();
}
inline void Request_RequestWrite_RequestWriteData::clear_attribute_data() {
  attribute_data_.Clear();
}
inline const ::stringdb::Request_RequestWrite_RequestWriteData_AttributeData& Request_RequestWrite_RequestWriteData::attribute_data(int index) const {
  return attribute_data_.Get(index);
}
inline ::stringdb::Request_RequestWrite_RequestWriteData_AttributeData* Request_RequestWrite_RequestWriteData::mutable_attribute_data(int index) {
  return attribute_data_.Mutable(index);
}
inline ::stringdb::Request_RequestWrite_RequestWriteData_AttributeData* Request_RequestWrite_RequestWriteData::add_attribute_data() {
  return attribute_data_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::stringdb::Request_RequestWrite_RequestWriteData_AttributeData >&
Request_RequestWrite_RequestWriteData::attribute_data() const {
  return attribute_data_;
}
inline ::google::protobuf::RepeatedPtrField< ::stringdb::Request_RequestWrite_RequestWriteData_AttributeData >*
Request_RequestWrite_RequestWriteData::mutable_attribute_data() {
  return &attribute_data_;
}

// -------------------------------------------------------------------

// Request_RequestWrite

// optional .stringdb.Request.RequestWrite.RequestWriteData request_write_data = 21;
inline bool Request_RequestWrite::has_request_write_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request_RequestWrite::set_has_request_write_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request_RequestWrite::clear_has_request_write_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request_RequestWrite::clear_request_write_data() {
  if (request_write_data_ != NULL) request_write_data_->::stringdb::Request_RequestWrite_RequestWriteData::Clear();
  clear_has_request_write_data();
}
inline const ::stringdb::Request_RequestWrite_RequestWriteData& Request_RequestWrite::request_write_data() const {
  return request_write_data_ != NULL ? *request_write_data_ : *default_instance_->request_write_data_;
}
inline ::stringdb::Request_RequestWrite_RequestWriteData* Request_RequestWrite::mutable_request_write_data() {
  set_has_request_write_data();
  if (request_write_data_ == NULL) request_write_data_ = new ::stringdb::Request_RequestWrite_RequestWriteData;
  return request_write_data_;
}
inline ::stringdb::Request_RequestWrite_RequestWriteData* Request_RequestWrite::release_request_write_data() {
  clear_has_request_write_data();
  ::stringdb::Request_RequestWrite_RequestWriteData* temp = request_write_data_;
  request_write_data_ = NULL;
  return temp;
}
inline void Request_RequestWrite::set_allocated_request_write_data(::stringdb::Request_RequestWrite_RequestWriteData* request_write_data) {
  delete request_write_data_;
  request_write_data_ = request_write_data;
  if (request_write_data) {
    set_has_request_write_data();
  } else {
    clear_has_request_write_data();
  }
}

// -------------------------------------------------------------------

// Request

// required .stringdb.RequestAndResponseType type = 1;
inline bool Request::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::stringdb::RequestAndResponseType Request::type() const {
  return static_cast< ::stringdb::RequestAndResponseType >(type_);
}
inline void Request::set_type(::stringdb::RequestAndResponseType value) {
  assert(::stringdb::RequestAndResponseType_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional .stringdb.Request.RequestRead request_read = 21;
inline bool Request::has_request_read() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Request::set_has_request_read() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Request::clear_has_request_read() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Request::clear_request_read() {
  if (request_read_ != NULL) request_read_->::stringdb::Request_RequestRead::Clear();
  clear_has_request_read();
}
inline const ::stringdb::Request_RequestRead& Request::request_read() const {
  return request_read_ != NULL ? *request_read_ : *default_instance_->request_read_;
}
inline ::stringdb::Request_RequestRead* Request::mutable_request_read() {
  set_has_request_read();
  if (request_read_ == NULL) request_read_ = new ::stringdb::Request_RequestRead;
  return request_read_;
}
inline ::stringdb::Request_RequestRead* Request::release_request_read() {
  clear_has_request_read();
  ::stringdb::Request_RequestRead* temp = request_read_;
  request_read_ = NULL;
  return temp;
}
inline void Request::set_allocated_request_read(::stringdb::Request_RequestRead* request_read) {
  delete request_read_;
  request_read_ = request_read;
  if (request_read) {
    set_has_request_read();
  } else {
    clear_has_request_read();
  }
}

// optional .stringdb.Request.RequestWrite request_write = 22;
inline bool Request::has_request_write() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Request::set_has_request_write() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Request::clear_has_request_write() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Request::clear_request_write() {
  if (request_write_ != NULL) request_write_->::stringdb::Request_RequestWrite::Clear();
  clear_has_request_write();
}
inline const ::stringdb::Request_RequestWrite& Request::request_write() const {
  return request_write_ != NULL ? *request_write_ : *default_instance_->request_write_;
}
inline ::stringdb::Request_RequestWrite* Request::mutable_request_write() {
  set_has_request_write();
  if (request_write_ == NULL) request_write_ = new ::stringdb::Request_RequestWrite;
  return request_write_;
}
inline ::stringdb::Request_RequestWrite* Request::release_request_write() {
  clear_has_request_write();
  ::stringdb::Request_RequestWrite* temp = request_write_;
  request_write_ = NULL;
  return temp;
}
inline void Request::set_allocated_request_write(::stringdb::Request_RequestWrite* request_write) {
  delete request_write_;
  request_write_ = request_write;
  if (request_write) {
    set_has_request_write();
  } else {
    clear_has_request_write();
  }
}

// -------------------------------------------------------------------

// Response_ResponseRead_ResponseReadData_AttributeData

// required int32 attribute_id = 1;
inline bool Response_ResponseRead_ResponseReadData_AttributeData::has_attribute_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response_ResponseRead_ResponseReadData_AttributeData::set_has_attribute_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response_ResponseRead_ResponseReadData_AttributeData::clear_has_attribute_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response_ResponseRead_ResponseReadData_AttributeData::clear_attribute_id() {
  attribute_id_ = 0;
  clear_has_attribute_id();
}
inline ::google::protobuf::int32 Response_ResponseRead_ResponseReadData_AttributeData::attribute_id() const {
  return attribute_id_;
}
inline void Response_ResponseRead_ResponseReadData_AttributeData::set_attribute_id(::google::protobuf::int32 value) {
  set_has_attribute_id();
  attribute_id_ = value;
}

// required string attribute_value = 2;
inline bool Response_ResponseRead_ResponseReadData_AttributeData::has_attribute_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response_ResponseRead_ResponseReadData_AttributeData::set_has_attribute_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response_ResponseRead_ResponseReadData_AttributeData::clear_has_attribute_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response_ResponseRead_ResponseReadData_AttributeData::clear_attribute_value() {
  if (attribute_value_ != &::google::protobuf::internal::kEmptyString) {
    attribute_value_->clear();
  }
  clear_has_attribute_value();
}
inline const ::std::string& Response_ResponseRead_ResponseReadData_AttributeData::attribute_value() const {
  return *attribute_value_;
}
inline void Response_ResponseRead_ResponseReadData_AttributeData::set_attribute_value(const ::std::string& value) {
  set_has_attribute_value();
  if (attribute_value_ == &::google::protobuf::internal::kEmptyString) {
    attribute_value_ = new ::std::string;
  }
  attribute_value_->assign(value);
}
inline void Response_ResponseRead_ResponseReadData_AttributeData::set_attribute_value(const char* value) {
  set_has_attribute_value();
  if (attribute_value_ == &::google::protobuf::internal::kEmptyString) {
    attribute_value_ = new ::std::string;
  }
  attribute_value_->assign(value);
}
inline void Response_ResponseRead_ResponseReadData_AttributeData::set_attribute_value(const char* value, size_t size) {
  set_has_attribute_value();
  if (attribute_value_ == &::google::protobuf::internal::kEmptyString) {
    attribute_value_ = new ::std::string;
  }
  attribute_value_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Response_ResponseRead_ResponseReadData_AttributeData::mutable_attribute_value() {
  set_has_attribute_value();
  if (attribute_value_ == &::google::protobuf::internal::kEmptyString) {
    attribute_value_ = new ::std::string;
  }
  return attribute_value_;
}
inline ::std::string* Response_ResponseRead_ResponseReadData_AttributeData::release_attribute_value() {
  clear_has_attribute_value();
  if (attribute_value_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = attribute_value_;
    attribute_value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Response_ResponseRead_ResponseReadData_AttributeData::set_allocated_attribute_value(::std::string* attribute_value) {
  if (attribute_value_ != &::google::protobuf::internal::kEmptyString) {
    delete attribute_value_;
  }
  if (attribute_value) {
    set_has_attribute_value();
    attribute_value_ = attribute_value;
  } else {
    clear_has_attribute_value();
    attribute_value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// Response_ResponseRead_ResponseReadData

// required int32 application_id = 1;
inline bool Response_ResponseRead_ResponseReadData::has_application_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response_ResponseRead_ResponseReadData::set_has_application_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response_ResponseRead_ResponseReadData::clear_has_application_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response_ResponseRead_ResponseReadData::clear_application_id() {
  application_id_ = 0;
  clear_has_application_id();
}
inline ::google::protobuf::int32 Response_ResponseRead_ResponseReadData::application_id() const {
  return application_id_;
}
inline void Response_ResponseRead_ResponseReadData::set_application_id(::google::protobuf::int32 value) {
  set_has_application_id();
  application_id_ = value;
}

// repeated .stringdb.Response.ResponseRead.ResponseReadData.AttributeData attribute_data = 21;
inline int Response_ResponseRead_ResponseReadData::attribute_data_size() const {
  return attribute_data_.size();
}
inline void Response_ResponseRead_ResponseReadData::clear_attribute_data() {
  attribute_data_.Clear();
}
inline const ::stringdb::Response_ResponseRead_ResponseReadData_AttributeData& Response_ResponseRead_ResponseReadData::attribute_data(int index) const {
  return attribute_data_.Get(index);
}
inline ::stringdb::Response_ResponseRead_ResponseReadData_AttributeData* Response_ResponseRead_ResponseReadData::mutable_attribute_data(int index) {
  return attribute_data_.Mutable(index);
}
inline ::stringdb::Response_ResponseRead_ResponseReadData_AttributeData* Response_ResponseRead_ResponseReadData::add_attribute_data() {
  return attribute_data_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::stringdb::Response_ResponseRead_ResponseReadData_AttributeData >&
Response_ResponseRead_ResponseReadData::attribute_data() const {
  return attribute_data_;
}
inline ::google::protobuf::RepeatedPtrField< ::stringdb::Response_ResponseRead_ResponseReadData_AttributeData >*
Response_ResponseRead_ResponseReadData::mutable_attribute_data() {
  return &attribute_data_;
}

// -------------------------------------------------------------------

// Response_ResponseRead

// optional .stringdb.Response.ResponseRead.ResponseReadData response_read_data = 21;
inline bool Response_ResponseRead::has_response_read_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response_ResponseRead::set_has_response_read_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response_ResponseRead::clear_has_response_read_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response_ResponseRead::clear_response_read_data() {
  if (response_read_data_ != NULL) response_read_data_->::stringdb::Response_ResponseRead_ResponseReadData::Clear();
  clear_has_response_read_data();
}
inline const ::stringdb::Response_ResponseRead_ResponseReadData& Response_ResponseRead::response_read_data() const {
  return response_read_data_ != NULL ? *response_read_data_ : *default_instance_->response_read_data_;
}
inline ::stringdb::Response_ResponseRead_ResponseReadData* Response_ResponseRead::mutable_response_read_data() {
  set_has_response_read_data();
  if (response_read_data_ == NULL) response_read_data_ = new ::stringdb::Response_ResponseRead_ResponseReadData;
  return response_read_data_;
}
inline ::stringdb::Response_ResponseRead_ResponseReadData* Response_ResponseRead::release_response_read_data() {
  clear_has_response_read_data();
  ::stringdb::Response_ResponseRead_ResponseReadData* temp = response_read_data_;
  response_read_data_ = NULL;
  return temp;
}
inline void Response_ResponseRead::set_allocated_response_read_data(::stringdb::Response_ResponseRead_ResponseReadData* response_read_data) {
  delete response_read_data_;
  response_read_data_ = response_read_data;
  if (response_read_data) {
    set_has_response_read_data();
  } else {
    clear_has_response_read_data();
  }
}

// -------------------------------------------------------------------

// Response_ResponseWrite_ResponseWriteData_WriteData

// required int32 attribute_id = 1;
inline bool Response_ResponseWrite_ResponseWriteData_WriteData::has_attribute_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response_ResponseWrite_ResponseWriteData_WriteData::set_has_attribute_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response_ResponseWrite_ResponseWriteData_WriteData::clear_has_attribute_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response_ResponseWrite_ResponseWriteData_WriteData::clear_attribute_id() {
  attribute_id_ = 0;
  clear_has_attribute_id();
}
inline ::google::protobuf::int32 Response_ResponseWrite_ResponseWriteData_WriteData::attribute_id() const {
  return attribute_id_;
}
inline void Response_ResponseWrite_ResponseWriteData_WriteData::set_attribute_id(::google::protobuf::int32 value) {
  set_has_attribute_id();
  attribute_id_ = value;
}

// required int32 error_number = 2;
inline bool Response_ResponseWrite_ResponseWriteData_WriteData::has_error_number() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response_ResponseWrite_ResponseWriteData_WriteData::set_has_error_number() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response_ResponseWrite_ResponseWriteData_WriteData::clear_has_error_number() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response_ResponseWrite_ResponseWriteData_WriteData::clear_error_number() {
  error_number_ = 0;
  clear_has_error_number();
}
inline ::google::protobuf::int32 Response_ResponseWrite_ResponseWriteData_WriteData::error_number() const {
  return error_number_;
}
inline void Response_ResponseWrite_ResponseWriteData_WriteData::set_error_number(::google::protobuf::int32 value) {
  set_has_error_number();
  error_number_ = value;
}

// -------------------------------------------------------------------

// Response_ResponseWrite_ResponseWriteData

// required int32 application_id = 1;
inline bool Response_ResponseWrite_ResponseWriteData::has_application_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response_ResponseWrite_ResponseWriteData::set_has_application_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response_ResponseWrite_ResponseWriteData::clear_has_application_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response_ResponseWrite_ResponseWriteData::clear_application_id() {
  application_id_ = 0;
  clear_has_application_id();
}
inline ::google::protobuf::int32 Response_ResponseWrite_ResponseWriteData::application_id() const {
  return application_id_;
}
inline void Response_ResponseWrite_ResponseWriteData::set_application_id(::google::protobuf::int32 value) {
  set_has_application_id();
  application_id_ = value;
}

// repeated .stringdb.Response.ResponseWrite.ResponseWriteData.WriteData write_data = 21;
inline int Response_ResponseWrite_ResponseWriteData::write_data_size() const {
  return write_data_.size();
}
inline void Response_ResponseWrite_ResponseWriteData::clear_write_data() {
  write_data_.Clear();
}
inline const ::stringdb::Response_ResponseWrite_ResponseWriteData_WriteData& Response_ResponseWrite_ResponseWriteData::write_data(int index) const {
  return write_data_.Get(index);
}
inline ::stringdb::Response_ResponseWrite_ResponseWriteData_WriteData* Response_ResponseWrite_ResponseWriteData::mutable_write_data(int index) {
  return write_data_.Mutable(index);
}
inline ::stringdb::Response_ResponseWrite_ResponseWriteData_WriteData* Response_ResponseWrite_ResponseWriteData::add_write_data() {
  return write_data_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::stringdb::Response_ResponseWrite_ResponseWriteData_WriteData >&
Response_ResponseWrite_ResponseWriteData::write_data() const {
  return write_data_;
}
inline ::google::protobuf::RepeatedPtrField< ::stringdb::Response_ResponseWrite_ResponseWriteData_WriteData >*
Response_ResponseWrite_ResponseWriteData::mutable_write_data() {
  return &write_data_;
}

// -------------------------------------------------------------------

// Response_ResponseWrite

// optional .stringdb.Response.ResponseWrite.ResponseWriteData response_write_data = 21;
inline bool Response_ResponseWrite::has_response_write_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response_ResponseWrite::set_has_response_write_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response_ResponseWrite::clear_has_response_write_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response_ResponseWrite::clear_response_write_data() {
  if (response_write_data_ != NULL) response_write_data_->::stringdb::Response_ResponseWrite_ResponseWriteData::Clear();
  clear_has_response_write_data();
}
inline const ::stringdb::Response_ResponseWrite_ResponseWriteData& Response_ResponseWrite::response_write_data() const {
  return response_write_data_ != NULL ? *response_write_data_ : *default_instance_->response_write_data_;
}
inline ::stringdb::Response_ResponseWrite_ResponseWriteData* Response_ResponseWrite::mutable_response_write_data() {
  set_has_response_write_data();
  if (response_write_data_ == NULL) response_write_data_ = new ::stringdb::Response_ResponseWrite_ResponseWriteData;
  return response_write_data_;
}
inline ::stringdb::Response_ResponseWrite_ResponseWriteData* Response_ResponseWrite::release_response_write_data() {
  clear_has_response_write_data();
  ::stringdb::Response_ResponseWrite_ResponseWriteData* temp = response_write_data_;
  response_write_data_ = NULL;
  return temp;
}
inline void Response_ResponseWrite::set_allocated_response_write_data(::stringdb::Response_ResponseWrite_ResponseWriteData* response_write_data) {
  delete response_write_data_;
  response_write_data_ = response_write_data;
  if (response_write_data) {
    set_has_response_write_data();
  } else {
    clear_has_response_write_data();
  }
}

// -------------------------------------------------------------------

// Response

// required .stringdb.RequestAndResponseType type = 1;
inline bool Response::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::stringdb::RequestAndResponseType Response::type() const {
  return static_cast< ::stringdb::RequestAndResponseType >(type_);
}
inline void Response::set_type(::stringdb::RequestAndResponseType value) {
  assert(::stringdb::RequestAndResponseType_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional .stringdb.Response.ResponseRead response_read = 21;
inline bool Response::has_response_read() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response::set_has_response_read() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response::clear_has_response_read() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response::clear_response_read() {
  if (response_read_ != NULL) response_read_->::stringdb::Response_ResponseRead::Clear();
  clear_has_response_read();
}
inline const ::stringdb::Response_ResponseRead& Response::response_read() const {
  return response_read_ != NULL ? *response_read_ : *default_instance_->response_read_;
}
inline ::stringdb::Response_ResponseRead* Response::mutable_response_read() {
  set_has_response_read();
  if (response_read_ == NULL) response_read_ = new ::stringdb::Response_ResponseRead;
  return response_read_;
}
inline ::stringdb::Response_ResponseRead* Response::release_response_read() {
  clear_has_response_read();
  ::stringdb::Response_ResponseRead* temp = response_read_;
  response_read_ = NULL;
  return temp;
}
inline void Response::set_allocated_response_read(::stringdb::Response_ResponseRead* response_read) {
  delete response_read_;
  response_read_ = response_read;
  if (response_read) {
    set_has_response_read();
  } else {
    clear_has_response_read();
  }
}

// optional .stringdb.Response.ResponseWrite response_write = 22;
inline bool Response::has_response_write() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Response::set_has_response_write() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Response::clear_has_response_write() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Response::clear_response_write() {
  if (response_write_ != NULL) response_write_->::stringdb::Response_ResponseWrite::Clear();
  clear_has_response_write();
}
inline const ::stringdb::Response_ResponseWrite& Response::response_write() const {
  return response_write_ != NULL ? *response_write_ : *default_instance_->response_write_;
}
inline ::stringdb::Response_ResponseWrite* Response::mutable_response_write() {
  set_has_response_write();
  if (response_write_ == NULL) response_write_ = new ::stringdb::Response_ResponseWrite;
  return response_write_;
}
inline ::stringdb::Response_ResponseWrite* Response::release_response_write() {
  clear_has_response_write();
  ::stringdb::Response_ResponseWrite* temp = response_write_;
  response_write_ = NULL;
  return temp;
}
inline void Response::set_allocated_response_write(::stringdb::Response_ResponseWrite* response_write) {
  delete response_write_;
  response_write_ = response_write;
  if (response_write) {
    set_has_response_write();
  } else {
    clear_has_response_write();
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace stringdb

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::stringdb::RequestAndResponseType>() {
  return ::stringdb::RequestAndResponseType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_stringdb_2eproto__INCLUDED
